name: 'Unity - Builder'
author: Webber Takken <webber@takken.io>
description: 'Build Unity projects for different platforms.'
inputs: {}
outputs:
  buildPath:
    description: 'Path where the current platform has been built to.'
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'dist/index.js'
