codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 100% # don't require patch to have coverage per se
        base: auto

    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        flags:
          - unit
        paths:
          - 'src'

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: no
