kubectl delete jobs $(kubectl get jobs -o custom-columns=:.metadata.name)
kubectl delete cronjobs $(kubectl get cronjobs -o custom-columns=:.metadata.name)
kubectl delete pods $(kubectl get pods -o custom-columns=:.metadata.name)
kubectl delete pvc $(kubectl get pvc -o custom-columns=:.metadata.name)
kubectl delete secrets $(kubectl get secrets -o custom-columns=:.metadata.name)
