#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Enable colors in Powershell (has scrolling issue?)
#export FORCE_COLOR=1

# Check changed files
yarn lint-staged

# Compile the action
yarn build ; git add dist
