name: Cats 😺

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  aCatForCreatingThePullRequest:
    name: A cat for your effort!
    runs-on: ubuntu-latest
    steps:
      - uses: ruairidhwm/action-cats@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
