name: Kubernetes

on:
  push: { branches: [main] }
  pull_request_target:
    paths-ignore:
      - '.github/**'

env:
  GKE_ZONE: 'us-central1-c'
  GKE_REGION: 'us-central1'
  GKE_PROJECT: 'unitykubernetesbuilder'
  GKE_CLUSTER: 'unity-builder-cluster'

jobs:
  k8sBuilds:
    name: K8s build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - StandaloneWindows64
        unityLicense:
          - ${{ secrets.UNITY_LICENSE }}
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - name: Checkout (default)
        uses: actions/checkout@v2
        if: github.event.event_type != 'pull_request_target'
        with:
          lfs: true
      - name: Checkout (pull_request_target)
        uses: actions/checkout@v2
        if: github.event.event_type == 'pull_request_target'
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      ###########################
      #         Spin up         #
      ###########################
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '288.0.0'
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      - run: ./action/bootstrapper/ApplyClusterAndAcquireLock.sh ${{ env.GKE_PROJECT }} ${{ env.GKE_CLUSTER }} ${{ env.GKE_ZONE }}

      ###########################
      #          Build          #
      ###########################
      - uses: frostebite/File-To-Base64@master
        id: read-base64
        with:
          filePath: ~/.kube/config
      - uses: ./
        id: k8s-unity-build
        env:
          UNITY_LICENSE: ${{ matrix.unityLicense }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          kubeConfig: ${{ steps.read-base64.outputs.base64 }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: test-project
          unityVersion: 2019.3.15f1

      ###########################
      #          Upload         #
      ###########################
      - uses: frostebite/K8s-Download-Volume@master
        with:
          kubeConfig: ${{ steps.read-base64.outputs.base64 }}
          volume: ${{ steps.k8s-unity-build.outputs.volume }}
          sourcePath: repo/build/
      - uses: actions/upload-artifact@v2
        with:
          name: Kubernetes Build (${{ matrix.targetPlatform }})
          path: k8s-volume-download
          retention-days: 14

      ###########################
      #        Spin down        #
      ###########################
      - run: ./action/bootstrapper/ReleaseLockAndAttemptShutdown.sh ${{ env.GKE_PROJECT }} ${{ env.GKE_CLUSTER }} ${{ env.GKE_ZONE }}
        if: ${{ always() }}
