name: Versioning

on:
  release:
    types: [published, edited]

jobs:
  updateMajorTag:
    name: Update major tag
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
